In [1]:
import numpy as np

## Warm Up: Practice some NumPy commands:
- Create 3 * 3 array.
- Check its shape.
- Select first row.
- Select 2nd column.
- Select the 2nd element in the third column.
- Create 2*2 from the first two elements of the first 2 rows and columns.
- Create single row vector.
- Create single column vector.

In [2]:
array = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

In [3]:
array.shape

(3, 3)

In [4]:
array[0, :]

array([1, 2, 3])

In [5]:
array[:, 1]

array([2, 5, 8])

In [6]:
array[2, 1]

8

In [8]:
two_by_two = array[:2, :2]
two_by_two

array([[1, 2],
       [4, 5]])

In [10]:
single_row_vector = np.array([1, 2, 3])
single_row_vector

array([1, 2, 3])

In [12]:
single_column_vector = np.array([[1],
                                 [2],
                                 [3]])
single_column_vector

array([[1],
       [2],
       [3]])

## System of linear equations:
- The following system of linear equations can be represented as <b>Ax=b</b>.
- Define matrix <b>A</b> and vector <b>b</b> as numpy arrays.
- Print them out.
1. $$3x-y=2$$ $$x=4 $$
$$$$
2. $$3x-2y=7$$  $$2x-2y=2$$
$$$$
3. $$2x-2y+z=7$$  $$x+y+z=2$$  $$3x-2y-z=3$$ 

In [13]:
A1 = np.array([[3, -1],
               [1, 0]])

In [14]:
A1

array([[ 3, -1],
       [ 1,  0]])

In [15]:
b1 = np.array([[2],
               [4]])

In [16]:
b1

array([[2],
       [4]])

In [17]:
A2 = np.array([[3, -2],
               [2, -2]])

b2 = np.array([[7],
               [2]])

print("\nA2:")
print(A2)
print("b2:")
print(b2)


A2:
[[ 3 -2]
 [ 2 -2]]
b2:
[[7]
 [2]]


In [19]:
A3 = np.array([[3, -2, 1],
               [1, 1, 1],
               [3, -2, -1]])

b3 = np.array([[7],
               [2],
               [3]])

print("\nA3:")
print(A3)
print("b3:")
print(b3)


A3:
[[ 3 -2  1]
 [ 1  1  1]
 [ 3 -2 -1]]
b3:
[[7]
 [2]
 [3]]


A1:
[[ 3 -1]
 [ 1  0]]
b1:[[2]
 [4]]

A2:
[[ 3 -2]
 [ 2 -2]]
b1:[[7]
 [2]]

A3:
[[ 3 -2  1]
 [ 1  1  1]
 [ 3 -2 -1]]
b1:[[7]
 [2]
 [3]]


### Find a solution for the above systems of equations using:
<b>np.linalg.inv()</b>

***since Ax=b therefore x=A_inv.*b***

In [21]:
A1_inv = np.linalg.inv(A1)
A2_inv = np.linalg.inv(A2)
A3_inv = np.linalg.inv(A3)

x1 = np.dot(A1_inv, b1)
x2 = np.dot(A2_inv, b2)
x3 = np.dot(A3_inv, b3)

print("x1:")
print(x1)

print("x2")
print(x2)

print("x3")
print(x3)

x1:
[[ 4.]
 [10.]]
x2
[[5.]
 [4.]]
x3
[[ 1.]
 [-1.]
 [ 2.]]


x1= [[ 4.]
 [10.]] 

x2= [[5.]
 [4.]] 

x3= [[ 1.]
 [-1.]
 [ 2.]]


### Find a solution for the above systems of equations using:
<b>np.linalg.solve()</b>

In [24]:
x1 = np.linalg.solve(A1, b1)
x2 = np.linalg.solve(A2, b2)
x3 = np.linalg.solve(A3, b3)
print("x1=")
print(x1)

print("x2=")
print(x2)

print("x3=")
print(x3)

x1=
[[ 4.]
 [10.]]
x2=
[[5.]
 [4.]]
x3=
[[ 1.]
 [-1.]
 [ 2.]]


x1= [[ 4.]
 [10.]] 

x2= [[5.]
 [4.]] 

x3= [[ 1.]
 [-1.]
 [ 2.]]


## Using numpy arrays
- For the above systems of equations, multiply matrix <b>A</b> and vector <b>x</b> and make sure the result is <b>b</b>.

In [25]:
np.dot(A1, x1)

array([[2.],
       [4.]])

array([[2.],
       [4.]])

In [26]:
np.dot(A2, x2)

array([[7.],
       [2.]])

array([[7.],
       [2.]])

In [27]:
np.dot(A3, x3)

array([[7.],
       [2.],
       [3.]])

array([[7.],
       [2.],
       [3.]])

## Vector Norms

### Calculate using numpy linalg.norm().
- Calculate L1, L2, Lmax norms for the following vectors:
$$v_1=\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix},
v_2=\begin{bmatrix} 3 \\ 3 \\ 1 \\ 3 \end{bmatrix}$$
- Calculate L3 norm for the vector
$$v_3=\begin{bmatrix} 2 \\  3 \\ 4 \end{bmatrix}$$

In [33]:
v1 = np.array([1, 2, 3])
v2 = np.array([3, 3, 1 ,3])
v3 = np.array([2, 3, 4])

l1_norm_v1 = np.linalg.norm(v1, ord=1)
l2_norm_v1 = np.linalg.norm(v1, ord=2)
lmax_norm_v1 = np.linalg.norm(v1, ord=np.inf)
print("v1:")
print("L1:", l1_norm_v1)
print("L2:", l2_norm_v1)
print("Lmax:", lmax_norm_v1)

v1:
L1: 6.0
L2: 3.7416573867739413
Lmax: 3.0


In [34]:
l1_norm_v2 = np.linalg.norm(v2, ord=1)
l2_norm_v2 = np.linalg.norm(v2, ord=2)
lmax_norm_v2 = np.linalg.norm(v2, ord=np.inf)
print("v2:")
print("L1:", l1_norm_v2)
print("L2:", l2_norm_v2)
print("Lmax:", lmax_norm_v2)

v2:
L1: 10.0
L2: 5.291502622129181
Lmax: 3.0


In [36]:
l3_norm_v3 = np.linalg.norm(v3, ord=3)
print("v3:")
print("L3:", l3_norm_v3)

v3:
L3: 4.626065009182741


v1:
L1: 6.0
L2: 3.7416573867739413
Lmax: 3.0

v2:
L1: 10.0
L2: 5.291502622129181
Lmax: 3.0

v3:
L3: 4.626065009182741


### Calculate L1, L2, L3, and Lmax for the following vectors:
$$v_1=\begin{bmatrix} 5 \\ 6 \end{bmatrix},
v_2=\begin{bmatrix} 4 \\ 3 \\ 2 \end{bmatrix},
v_3=\begin{bmatrix} 4 \\ 3 \\ 2 \\ 8 \\ 9 \end{bmatrix}$$

In [37]:
v1 = np.array([5, 6, ])
v2 = np.array([4, 3, 2 ])
v3 = np.array([4, 3, 2 , 8, 9])

In [39]:
l1_norm_v1 = np.linalg.norm(v1, ord=1)
l2_norm_v1 = np.linalg.norm(v1, ord=2)
l3_norm_v1 = np.linalg.norm(v1, ord=3)
lmax_norm_v1 = np.linalg.norm(v1, ord=np.inf)
print("v1:")
print("L1:", l1_norm_v1)
print("L2:", l2_norm_v1)
print("L3:", l3_norm_v1)
print("Lmax:", lmax_norm_v1)

l1_norm_v2 = np.linalg.norm(v2, ord=1)
l2_norm_v2 = np.linalg.norm(v2, ord=2)
l3_norm_v2 = np.linalg.norm(v2, ord=3)
lmax_norm_v2 = np.linalg.norm(v2, ord=np.inf)
print("v2:")
print("L1:", l1_norm_v2)
print("L2:", l2_norm_v2)
print("L3:", l3_norm_v3)
print("Lmax:", lmax_norm_v2)

l1_norm_v3 = np.linalg.norm(v3, ord=1)
l2_norm_v3 = np.linalg.norm(v3, ord=2)
l3_norm_v3 = np.linalg.norm(v3, ord=3)
lmax_norm_v3 = np.linalg.norm(v3, ord=np.inf)
print("v3:")
print("L1:", l1_norm_v3)
print("L2:", l2_norm_v3)
print("L3:", l3_norm_v3)
print("Lmax:", lmax_norm_v3)

v1:
L1: 11.0
L2: 7.810249675906654
L3: 6.986368027818105
Lmax: 6.0
v2:
L1: 9.0
L2: 5.385164807134504
L3: 11.02473771449733
Lmax: 4.0
v3:
L1: 26.0
L2: 13.19090595827292
L3: 11.02473771449733
Lmax: 9.0


v1:
L1: 11.0
L2: 7.810249675906654
L3: 6.986368027818105
Lmax: 6.0

v2:
L1: 9.0
L2: 5.385164807134504
L3: 4.626065009182741
Lmax: 4.0

v3:
L1: 26.0
L2: 13.19090595827292
L3: 11.02473771449733
Lmax: 9.0


## Dot Product

### Calculate the dot product of the following vectors:
$$v_1=\begin{bmatrix} 2 \\ -1 \\ 5 \\ 0 \end{bmatrix} and
v_2=\begin{bmatrix} 4 \\ -3 \\ 1 \\ -1 \end{bmatrix}$$
### Calculate the dot product of the following vectors and explain the result:
$$v_1=\begin{bmatrix} 3 \\ 2 \\ -1 \\ 4 \end{bmatrix} and
v_2=\begin{bmatrix} 1 \\ -1 \\ 1 \\ 0 \end{bmatrix} $$ 

In [40]:
v1 = np.array([2, -1, 5, 0])
v2 = np.array([4, -3, 1 ,-1])

In [41]:
v1@v2

16

16

In [42]:
v1 = np.array([3, 2, -1, 4])
v2 = np.array([1, -1, 1 ,0])

In [43]:
v1@v2

0

0

### Create two vectors in 2, 3, and 4 dimensions.
### Perform vector addition, subtraction, and dot product of these vectors.

In [194]:
v2_a = np.array([1, 2])
v2_b = np.array([-3, 4])

addition_result_2d = v2_a + v2_b
subtraction_result_2d = v2_a - v2_b
dot_product_2d = np.dot(v2_a, v2_b)


v3_a = np.array([2, -1, 3])
v3_b = np.array([0, 1, -2])

addition_result_3d = v3_a + v3_b
subtraction_result_3d = v3_a - v3_b
dot_product_3d = np.dot(v3_a, v3_b)


v4_a = np.array([1, 2, -1, 4])
v4_b = np.array([3, -2, 0, 1])

addition_result_4d = v4_a + v4_b
subtraction_result_4d = v4_a - v4_b
dot_product_4d = np.dot(v4_a, v4_b)

In [193]:
print("2D:")
print("Addition:", addition_result_2d)
print("Subtraction:", subtraction_result_2d)
print("Dot Product:", dot_product_2d)

print("3D:")

print( addition_result_3d)
print( subtraction_result_3d)
print( dot_product_3d)

print("4D:")
print(addition_result_4d)
print(subtraction_result_4d)
print(dot_product_4d)

2D:
Addition: [-2  6]
Subtraction: [ 4 -2]
Dot Product: 5
3D:
[2 0 1]
[ 2 -2  5]
-7
4D:
[ 4  0 -1  5]
[-2  4 -1  3]
3


## Matrix Operations

### Matrix Multiplication AB then Transpose the result.
$$A=\begin{bmatrix} 3&1&0 \\ 2&1&2 \end{bmatrix}, B=\begin{bmatrix} 1&3 \\ 2&5 \\ -1&3 \end{bmatrix}$$
$$A=\begin{bmatrix} 1&0&3 \\ 4&5&-1 \\ 0&0&2  \end{bmatrix}, B=\begin{bmatrix} 1\\2\\5 \end{bmatrix}$$

In [195]:
A = np.array([[3, 1, 0],
              [2, 1, 2]])

B = np.array([[1, 3],
              [2, 5],
              [-1,3]])
C1 = np.dot(A, B)
C1_transpose = np.transpose(C1)

C2 = np.array([[16],
               [9],
               [10]])
C2_transpose = np.transpose(C2)


print("C1:")
print(C1)

print("C1_transpose:")
print(C1_transpose)

print("C2:")
print(C2)

print("C2_transpose:")
print(C2_transpose)

C1:
[[ 5 14]
 [ 2 17]]
C1_transpose:
[[ 5  2]
 [14 17]]
C2:
[[16]
 [ 9]
 [10]]
C2_transpose:
[[16  9 10]]


C1:
[[ 5 14]
 [ 2 17]]

C1_transpose:
[[ 5  2]
 [14 17]]

C2:
[[16]
 [ 9]
 [10]]

C2_transpose:
[[16  9 10]]


## Different Types of Matrices
### Create 3 by 3 and 4 by 4 identity matrices 

In [52]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Create a diagonal matrix contains [2,4,5,11] numbers in its diagonal.

In [54]:
diagonal_elements = [2, 4, 5, 11]
np.diag(diagonal_elements)

array([[ 2,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  5,  0],
       [ 0,  0,  0, 11]])

array([[ 2,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  5,  0],
       [ 0,  0,  0, 11]])

### Create a 5 by 5 scalar matrix of number 7

In [56]:
np.diag([7] * 5)

array([[7, 0, 0, 0, 0],
       [0, 7, 0, 0, 0],
       [0, 0, 7, 0, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 7]])

array([[7., 0., 0., 0., 0.],
       [0., 7., 0., 0., 0.],
       [0., 0., 7., 0., 0.],
       [0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 7.]])

### Using SymPy get the rref of the following matrices

In [58]:
pip install sympy


[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: C:\Users\HP\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip



     ---------------------------------------- 5.7/5.7 MB 409.4 kB/s eta 0:00:00
     ------------------------------------ 536.2/536.2 kB 267.1 kB/s eta 0:00:00


In [59]:
from sympy import Matrix

In [62]:
matrix = Matrix([
    [1, 0, 1, 3],
    [2, 3, 4, 7],
    [-1, -3, -3, -4]
])

In [63]:
matrix

Matrix([
[ 1,  0,  1,  3],
[ 2,  3,  4,  7],
[-1, -3, -3, -4]])

Matrix([
[ 1,  0,  1,  3],
[ 2,  3,  4,  7],
[-1, -3, -3, -4]])

In [111]:
matrix = Matrix([
    [1, 2, 3],
    [2, -1, 1],
    [3,0,-1]
])


print("Original Matrix:")
print(matrix)

print("Reduced Row-Echelon Form (rref):")
print(rref_matrix)

print("Pivot Columns:")
print(pivot_columns)

Original Matrix:
Matrix([[1, 2, 3], [2, -1, 1], [3, 0, -1]])

Reduced Row-Echelon Form (rref):
Matrix([[1, 0, 0, 3], [0, 1, 0, 2], [0, 0, 1, 1]])

Pivot Columns:
(0, 1, 2)


In [70]:
matrix = Matrix([
    [1, 2, 3],
    [2, -1, 1],
    [3,0,-1]
])

In [71]:
matrix

Matrix([
[1,  2,  3],
[2, -1,  1],
[3,  0, -1]])

In [77]:
matrix.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

Matrix([
[1,  2,  3],
[2, -1,  1],
[3,  0, -1]])

Matrix([
[ 1,  0,  1,  3],
[ 2,  3,  4,  7],
[-1, -3, -3, -4]])

(Matrix([
 [1, 0,   1,   3],
 [0, 1, 2/3, 1/3],
 [0, 0,   0,   0]]),
 (0, 1))

Matrix([
[1, 1, 1],
[1, 2, 2],
[1, 2, 3]])

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

Matrix([
[1,  2,  3],
[2, -1,  1],
[3,  0, -1]])

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

### Find the solution of the following system of linear equation using SymPy Matrix rref()
#### Write down the solution as a python note e.g., x=1, y=4, and z=10

1. $$x+y+z=6$$  $$x+2y+2z=9$$  $$x+2y+3z=10$$ 
$$$$
2. $$x+2y+3z=9$$  $$2x-y+z=8$$  $$3x-z=3$$ 

In [83]:
matrix = Matrix([
    [1, 1, 1, 6],
    [1, 2, 2, 9],
    [1, 2, 3, 10]
])
matrix

Matrix([
[1, 1, 1,  6],
[1, 2, 2,  9],
[1, 2, 3, 10]])

Matrix([
[1, 1, 1,  6],
[1, 2, 2,  9],
[1, 2, 3, 10]])

In [84]:
matrix.rref()

(Matrix([
 [1, 0, 0, 3],
 [0, 1, 0, 2],
 [0, 0, 1, 1]]),
 (0, 1, 2))

In [ ]:
z=1,y=2,x=3

(Matrix([
 [1, 0, 0, 3],
 [0, 1, 0, 2],
 [0, 0, 1, 1]]),
 (0, 1, 2))

In [86]:
matrix = Matrix([
    [1, 2, 3, 9],
    [2, -1, 1, 8],
    [3, 0, -1, 3]
])
matrix

Matrix([
[1,  2,  3, 9],
[2, -1,  1, 8],
[3,  0, -1, 3]])

Matrix([
[1,  2,  3, 9],
[2, -1,  1, 8],
[3,  0, -1, 3]])

In [87]:
matrix.rref()

(Matrix([
 [1, 0, 0,  2],
 [0, 1, 0, -1],
 [0, 0, 1,  3]]),
 (0, 1, 2))

In [ ]:
z=3,y=-1,x=2

(Matrix([
 [1, 0, 0,  2],
 [0, 1, 0, -1],
 [0, 0, 1,  3]]),
 (0, 1, 2))

In [107]:
r=matrix.rref()

In [ ]:
x=1,y=-1,z=3

### Find the solution of the following system of linear equation using SymPy Matrix rref()
#### Write down the solution as a python note e.g., x=1, y=4, and z=10

1. $$x-2y=1$$ $$3x-6y=11 $$
$$$$
2. $$x-2y=1$$ $$3x-6y=3 $$
$$$$
3. $$x+2y+3z=6$$  $$2x+5y+2z=4$$  $$6x-3y+z=2$$ 
$$$$
4. $$2x+4y-2z=2$$  $$4x+9y-3z=8$$  $$-2x-3y+7z=10$$ 

In [89]:
matrix = Matrix([
    [1, -2, 1],
    [3, -6, 11],
   ])
matrix

Matrix([
[1, -2,  1],
[3, -6, 11]])

Matrix([
[1, -2,  1],
[3, -6, 11]])

In [90]:
matrix.rref()

(Matrix([
 [1, -2, 0],
 [0,  0, 1]]),
 (0, 2))

In [ ]:
#inconsistent solution

(Matrix([
 [1, -2, 0],
 [0,  0, 1]]),
 (0, 2))

In [91]:
matrix = Matrix([
    [1, -2, 1],
    [3, -6, 3],
   ])
matrix

Matrix([
[1, -2, 1],
[3, -6, 3]])

Matrix([
[1, -2, 1],
[3, -6, 3]])

In [92]:
matrix.rref()

(Matrix([
 [1, -2, 1],
 [0,  0, 0]]),
 (0,))

In [ ]:
#infinite number of solutions

(Matrix([
 [1, -2, 1],
 [0,  0, 0]]),
 (0,))

In [189]:
matrix = Matrix([
    [1, 2, 3, 6],
    [2, 5, 2, 4],
    [6, -3, 1, 2],
   ])
matrix

Matrix([
[1,  2, 3, 6],
[2,  5, 2, 4],
[6, -3, 1, 2]])

Matrix([
[1,  2, 3, 6],
[2,  5, 2, 4],
[6, -3, 1, 2]])

In [190]:
matrix.rref()

(Matrix([
 [1, 0, 0, 0],
 [0, 1, 0, 0],
 [0, 0, 1, 2]]),
 (0, 1, 2))

In [ ]:
z=2,y=0,x=0

(Matrix([
 [1, 0, 0, 0],
 [0, 1, 0, 0],
 [0, 0, 1, 2]]),
 (0, 1, 2))

In [99]:
matrix = Matrix([
    [2, 4, -2, 2],
    [4, 9, -3, 8],
    [-2, -3, 7, 10],
   ])
matrix

Matrix([
[ 2,  4, -2,  2],
[ 4,  9, -3,  8],
[-2, -3,  7, 10]])

Matrix([
[ 2,  4, -2,  2],
[ 4,  9, -3,  8],
[-2, -3,  7, 10]])

In [100]:
matrix.rref()

(Matrix([
 [1, 0, 0, -1],
 [0, 1, 0,  2],
 [0, 0, 1,  2]]),
 (0, 1, 2))

In [ ]:
z=2,y=2,x=-1

(Matrix([
 [1, 0, 0, -1],
 [0, 1, 0,  2],
 [0, 0, 1,  2]]),
 (0, 1, 2))

In [187]:
r=matrix.rref()

In [188]:
r

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

In [ ]:
y

In [191]:
m = Matrix([
    [2, 4, -2, 2],
    [4, 9, -3, 8],
    [-2, -3, 7, 10],
   ])
matrix

Matrix([
[1,  2, 3, 6],
[2,  5, 2, 4],
[6, -3, 1, 2]])

In [192]:
matrix.rref()

(Matrix([
 [1, 0, 0, 0],
 [0, 1, 0, 0],
 [0, 0, 1, 2]]),
 (0, 1, 2))

In [ ]:
z=2,y=0,x=1

In [120]:
#HOMEWORK

In [109]:
A = np.array([[0, 1, 1],
               [1, 0, 1],
               [1, 1, 0]])


In [112]:
B = np.array([[0, 2, 3],
               [0, 5, 0],
               [7, 0, 0]])

In [114]:
product = np.multiply(A, B)
product 

array([[ 0,  4,  9],
       [ 0, 25,  0],
       [49,  0,  0]])

In [115]:
np.add(A, B)

array([[ 0,  4,  6],
       [ 0, 10,  0],
       [14,  0,  0]])

In [116]:
np.transpose(A)

array([[0, 0, 7],
       [2, 5, 0],
       [3, 0, 0]])

In [117]:
A[1, :]

array([0, 5, 0])

In [118]:
a = A[:, -1]
b = B[-1, :]

In [119]:
np.add(a, b)

array([10,  0,  0])

In [130]:
v = np.array([2, 4, 1])

In [131]:
u = np.array([1, 3, 5])

In [132]:
dot_product = np.dot(v.T, u)
dot_product

19

In [133]:
norm_L1_v = np.linalg.norm(v, ord=1)
norm_L2_v = np.linalg.norm(v, ord=2)
norm_L3_v = np.linalg.norm(v, ord=3)
norm_L4_v = np.linalg.norm(v, ord=4)
norm_max_v = np.linalg.norm(v, ord=np.inf)
print("L1 Norm:", norm_L1_v)
print("L2 Norm:", norm_L2_v)
print("L3 Norm:", norm_L3_v)
print("L4 Norm:", norm_L4_v)
print("Max Norm:", norm_max_v)

L1 Norm: 7.0
L2 Norm: 4.58257569495584
L3 Norm: 4.179339196381232
L4 Norm: 4.064813850824944
Max Norm: 4.0


In [136]:
norm_L1_u = np.linalg.norm(u, ord=1)
norm_L2_u = np.linalg.norm(u, ord=2)
norm_L3_u = np.linalg.norm(u, ord=3)
norm_L4_u = np.linalg.norm(u, ord=4)
norm_max_u = np.linalg.norm(u, ord=np.inf)

print("u:")
print("L1 Norm:", norm_L1_u)
print("L2 Norm:", norm_L2_u)
print("L3 Norm:", norm_L3_u)
print("L4 Norm:", norm_L4_u)
print("Max Norm:", norm_max_u)

u:
L1 Norm: 9.0
L2 Norm: 5.916079783099616
L3 Norm: 5.348481241239363
L4 Norm: 5.156497997732246
Max Norm: 5.0


In [141]:
sum_vector = v + u

In [143]:
print(sum_vector)

[3 7 6]


In [138]:
norm_sum_vector = np.linalg.norm(sum_vector)

In [140]:
print(norm_sum_vector)

9.695359714832659


In [144]:
Matrix(A).rref()

(Matrix([
 [1],
 [0],
 [0]]),
 (0,))

In [145]:
Matrix(B).rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

In [146]:
augmented_matrix = Matrix([[2, 3, 1],
                           [10, 9, 11]])

In [147]:
rref_matrix, pivot_columns = augmented_matrix.rref()

In [148]:
print(rref_matrix)

Matrix([[1, 0, 2], [0, 1, -1]])


In [149]:
x_val = rref_matrix[0, -1]
y_val = rref_matrix[1, -1]

In [150]:
print("x =", x_val)
print("y =", y_val)

x = 2
y = -1


In [151]:
augmented_matrix = Matrix([[2, -4, 6],
                           [-1, 5, 0]])

In [153]:
rref_matrix, pivot_columns = augmented_matrix.rref()
rref_matrix

Matrix([
[1, 0, 5],
[0, 1, 1]])

In [154]:
A = Matrix([[1, 1, 1],
            [1, 2, 1],
            [0, 1, 2]])

In [155]:
A.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

In [156]:
A = Matrix([[1, 1, 1, 7],
            [1, 1, -1, 5],
            [1, -1, 1, 3]])

In [158]:
A.rref()

(Matrix([
 [1, 0, 0, 4],
 [0, 1, 0, 2],
 [0, 0, 1, 1]]),
 (0, 1, 2))

In [ ]:
therefore y=1,x=2,z=4

In [161]:
A = Matrix([[1, 1, 1, 7],
            [1, 1, -1, 5],
            [-1, -1, 1, 3]])

In [162]:
A.rref()

(Matrix([
 [1, 1, 0, 0],
 [0, 0, 1, 0],
 [0, 0, 0, 1]]),
 (0, 2, 3))

In [164]:
#no solution since 0 != 1

In [ ]:
#QUIZ

In [166]:
u = np.array([4, -3])
v = np.array([3, 2])

result = u + v
result

array([ 7, -1])

In [167]:
l1_norm_u = np.linalg.norm(u, ord=1)
l2_norm_u = np.linalg.norm(u, ord=2)
l3_norm_u = np.linalg.norm(u, ord=3)
linf_norm_u = np.linalg.norm(u, ord=np.inf)

In [168]:
print("U Norms:")
print("L1", l1_norm_u)
print("L2", l2_norm_u)
print("L3", l3_norm_u)
print("L", linf_norm_u)

U Norms:
L1 7.0
L2 5.0
L3 4.497941445275415
L 4.0


In [169]:
l1_norm_v = np.linalg.norm(v, ord=1)
l2_norm_v = np.linalg.norm(v, ord=2)
l3_norm_v = np.linalg.norm(v, ord=3)
linf_norm_v = np.linalg.norm(v, ord=np.inf)

In [170]:
print("norm of v:", l1_norm_v)
print("L2", l2_norm_v)
print("L3", l3_norm_v)
print("L", linf_norm_v)

norm of v: 5.0
L2 3.605551275463989
L3 3.2710663101885897
L 3.0


In [171]:
u_plus_v = u + v

l1_norm_u_plus_v = np.linalg.norm(u_plus_v, ord=1)
l2_norm_u_plus_v = np.linalg.norm(u_plus_v, ord=2)
l3_norm_u_plus_v = np.linalg.norm(u_plus_v, ord=3)
linf_norm_u_plus_v = np.linalg.norm(u_plus_v, ord=np.inf)

In [172]:
print("norm of u + v:", l1_norm_u_plus_v)
print("L2", l2_norm_u_plus_v)
print("L3", l3_norm_u_plus_v)
print("L", linf_norm_u_plus_v)

norm of u + v: 8.0
L2 7.0710678118654755
L3 7.006796120773448
L 7.0


In [173]:
dot_product_uv = np.dot(u, v)
dot_product_uv

6

In [175]:
A = np.array([[-3, 2, -5], [2, -3, 4], [1, 1, 1]])
B = np.array([14, 10, 14])
x = np.linalg.solve(A, B)
x

array([-1.59727667e+17,  4.56364762e+16,  1.14091191e+17])

In [176]:
A_matrix = np.array([[2, 1, 3], [3, -2, 1], [-1, 0, 1]])
B_matrix = np.array([[1, -2], [2, 1], [4, -2]])
AB_matrix = np.dot(A_matrix, B_matrix)
AB_matrix 

array([[ 16,  -9],
       [  3, -10],
       [  3,   0]])

In [181]:
import sympy as sp

In [182]:
A_matrix = sp.Matrix([
    [2, 1, 3],
    [3, -2, 1],
    [-1, 0, 1]
])

B_matrix = sp.Matrix([
    [1, -2],
    [2, 1],
    [4, -2]
])

In [183]:
A_matrix.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

In [184]:
B_matrix.rref()

(Matrix([
 [1, 0],
 [0, 1],
 [0, 0]]),
 (0, 1))

In [ ]:
AAA