## Linear Combination
### Use NumPy

$$v_1=\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix},
v_2=\begin{bmatrix} 3 \\ 5 \\ 1 \end{bmatrix},
v_3=\begin{bmatrix} 0 \\ 0 \\ 8 \end{bmatrix}$$
- Find <b>b</b> vector where $$b=3v_1+0v_2+0v_3$$
- Find <b>x</b> vector where $$x=-v_1+v_2-0.5v_3$$

In [2]:
import numpy as np

In [3]:
v1 = np.array([[1], [2], [3]])
v2 = np.array([[3], [5], [1]])
v3 = np.array([[0], [0], [8]])

In [5]:
b = 3 * v1 + 0 * v2 + 0 * v3
print(b)

[[3]
 [6]
 [9]]


In [6]:
x = -v1 + v2 - 0.5 * v3
print(x)

[[ 2.]
 [ 3.]
 [-6.]]


b:
[[3]
 [6]
 [9]]

x:
[[ 2.]
 [ 3.]
 [-6.]]


## Vector Span
### Use Numpy (matrix inverse) and SymPy (rref)

#### Is $$v=\begin{bmatrix} 19 \\ 10 \\ -1 \end{bmatrix}$$ in the span of 
$$v_1=\begin{bmatrix} 3 \\ -1 \\ 2 \end{bmatrix},
v_2=\begin{bmatrix} -5 \\ 0 \\ 1 \end{bmatrix},
v_3=\begin{bmatrix} 1 \\ 7 \\ -4 \end{bmatrix}$$

In [13]:
from sympy import Matrix

In [8]:
v = np.array([[19], [10], [-1]])
v1 = np.array([[3], [-1], [2]])
v2 = np.array([[-5], [0], [1]])
v3 = np.array([[1], [7], [-4]])

In [21]:
matrix=Matrix([ [3, -5,  1, 19],
            [-1,  0,  7, 10],
             [ 2,  1, -4, -1]])

In [22]:
matrix.rref()

(Matrix([
 [1, 0, 0,  4],
 [0, 1, 0, -1],
 [0, 0, 1,  2]]),
 (0, 1, 2))

(Matrix([
 [1, 0, 0,  4],
 [0, 1, 0, -1],
 [0, 0, 1,  2]]),
 (0, 1, 2))

In [23]:
A = np.column_stack((v1, v2, v3))

In [24]:
scalars = np.linalg.solve(A, v)
scalars

array([[ 4.],
       [-1.],
       [ 2.]])

[[ 4.]
 [-1.]
 [ 2.]]


## Vector Linear Independence
### Use rref and determinant
- Consider the following sets of vectors in R3. If the set is independent, prove it. 
- If the set is dependent, find a nontrivial linear combination of the vectors which is equal to 0.
    - {(2, 0, -3), (1, 1, 1), (1, 7, 2)}.
    - {(1, 2, -1), (4, 1, 3), (-10, 1, -11)}.

<b>Hint: we have to determine whether this implies that 𝒂=𝒃=𝒄=𝟎.</b>

In [91]:
matrix = Matrix([
              [2,0,-3], 
              [1,1,1],
              [1,7,2],
              ])

In [92]:
matrix.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

In [ ]:
# it is linearly independent

In [93]:
matrix = Matrix([
              [1,2,-1], 
              [4,1,3],
              [-10,1,-11],
              ])

In [94]:
matrix.rref()

(Matrix([
 [1, 0,  1],
 [0, 1, -1],
 [0, 0,  0]]),
 (0, 1))

In [ ]:
#linearly dependent

In [25]:
A1 = np.array([[2, 0, -3], [1, 1, 1], [1, 7, 2]])

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

In [98]:
M = Matrix([[1,4,-10],
            [2,1,1],
            [-1,3,-11]])

In [99]:
M.rref()

(Matrix([
 [1, 0,  2],
 [0, 1, -3],
 [0, 0,  0]]),
 (0, 1))

(Matrix([
 [1, 0,  2],
 [0, 1, -3],
 [0, 0,  0]]),
 (0, 1))

## Linear Transformation
### Ex.1

$$T=\begin{bmatrix} 1&2 \\ 3&7 \end{bmatrix}$$
- Write the linear transformation expression of this matrix. i.e. Linear functions of x,y. 
- Apply the transformation matrix <b>T</b> to the following vectors:
$$\begin{bmatrix} 1 \\ 0 \end{bmatrix},\begin{bmatrix} 0 \\ 1 \end{bmatrix} $$
- Find all points <b>(x,y)</b> such that <b>T(x,y)=(1,0)</b>

In [100]:
T = np.array([[1, 2], [3, 7]])

In [101]:
e1 = np.array([1, 0])

In [102]:
e2 = np.array([0, 1])

In [103]:
result_vector1 = np.dot(T, e1)
result_vector2 = np.dot(T, e2)

In [104]:
result_vector1

array([1, 3])

In [105]:
result_vector2

array([2, 7])

In [106]:
vector_output = np.array([1, 0])

In [107]:
solution = np.linalg.solve(T, vector_output)
solution

array([ 7., -3.])

A.v1=
[[1]
 [3]]

A.v2=
[[2]
 [7]]


(x,y):
[[ 7.]
 [-3.]]


### Ex.2
### For the expression $$T\begin{bmatrix} x \\ y \end{bmatrix}=\begin{bmatrix} x+y \\ y \end{bmatrix}$$
- Find the transformation matrix.
- Represent the transformation graphically <b>(on paper)</b>.
- Find all points <b>(x,y)</b> such that <b>T(x,y)=(3,4)</b>

In [ ]:
For [1,0] x+y:y = [1,0]

In [ ]:
For [0,1] x+y:y = [1,1]

In [110]:
T=[[1,1],[0,1]]

In [111]:
vector_output = np.array([3, 4])

In [112]:
solution = np.linalg.solve(T, vector_output)
solution

array([-1.,  4.])

x:
[[-1.]
 [ 4.]]


## Determinant
### Find Determinant of:

$$\begin{bmatrix} 3&8 \\ 4&6 \end{bmatrix} , \begin{bmatrix} 4&6 \\ 3&8 \end{bmatrix}$$
$$\begin{bmatrix} 6&1&1 \\ 4&-2&5 \\ 2&8&7\end{bmatrix}$$
$$\begin{bmatrix} 3&2&0&1 \\ 4&0&1&2 \\ 3&0&2&1 \\ 9&2&3&1\end{bmatrix}$$


In [ ]:
A1 = np.array([[3, 8], 
               [4,6]])
A2 = np.array([[4, 6], 
               [3,8]])
A3 = np.array([[6, 1, 1], 
               [4,-2, 5],
              [2, 8, 7]])
A4 = np.array([[3, 2, 0, 1], 
               [4, 0, 1, 2],
              [3, 0, 2, 1],
              [9, 2, 3, 1]])

In [59]:
det_A1 = np.linalg.det(A1)
det_A2 = np.linalg.det(A2)
det_A3 = np.linalg.det(A3)
det_A4 = np.linalg.det(A4)

print("A1:", det_A1)
print("A2:", det_A2)
print("A3:", det_A3)
print("A4:", det_A4)

A1: -14.000000000000004
A2: 14.000000000000004
A3: -306.0
A4: 24.000000000000004


1.  -14.000000000000004
2.  14.000000000000004
3.  -306.0
4.  24.000000000000004


## Matrix Rank
### Find the rank of the matrix (use rref and confirm using matrix_rank())

$$X = \begin{bmatrix} 1&2&4&4 \\ 3&4&8&0 \end{bmatrix}$$
$$Y = \begin{bmatrix} 1&2&3 \\ 2&3&5 \\ 3&4&7 \\ 4&5&9  \end{bmatrix}$$

In [39]:
X = Matrix([[1, 2, 4, 4], [3, 4, 8, 0]])

In [41]:
X.rref()

(Matrix([
 [1, 0, 0, -8],
 [0, 1, 2,  6]]),
 (0, 1))

In [43]:
rref_X, pivot_columns = X.rref()

In [45]:
print(f'X rank is {len(pivot_columns)}')

X rank is 2


(Matrix([
[1, 0, 0, -8],
[0, 1, 2,  6]]), (0, 1))

X rank: 2


In [58]:
rank_X = np.linalg.matrix_rank(np.array([[1, 2, 4, 4], [3, 4, 8, 0]])
)
rank_X

2

In [53]:
Y = Matrix([[1, 2, 3], [2, 3, 5], [3, 4, 7], [4, 5, 9]])
print(Y.rref())
rref_Y, pivot_columns = Y.rref()
print(f'Y rank is {len(pivot_columns)}')

(Matrix([
[1, 0, 1.0],
[0, 1, 1.0],
[0, 0,   0],
[0, 0,   0]]), (0, 1))
Y rank is 2


(Matrix([
[1, 0, 1],
[0, 1, 1],
[0, 0, 0],
[0, 0, 0]]), (0, 1))

Y rank: 2


In [57]:
rank_Y = np.linalg.matrix_rank(np.array([[1, 2, 3], [2, 3, 5], [3, 4, 7], [4, 5, 9]])
)
rank_Y

2

## Matrix Inverse
### Find the inverse:

$$\begin{bmatrix} 3&8 \\ 4&6 \end{bmatrix} , \begin{bmatrix} 4&6 \\ 3&8 \end{bmatrix}$$
$$\begin{bmatrix} 6&1&1 \\ 4&-2&5 \\ 2&8&7\end{bmatrix}$$
$$\begin{bmatrix} 3&2&0&1 \\ 4&0&1&2 \\ 3&0&2&1 \\ 9&2&3&1\end{bmatrix}$$

In [31]:
A1 = np.array([[3, 8], 
               [4,6]])
inverse_A1 = np.linalg.inv(A1)
inverse_A1

array([[-0.42857143,  0.57142857],
       [ 0.28571429, -0.21428571]])

In [32]:
A2 = np.array([[4, 6], 
               [3,8]])
inverse_A2 = np.linalg.inv(A2)
inverse_A2

array([[ 0.57142857, -0.42857143],
       [-0.21428571,  0.28571429]])

In [33]:
A3 = np.array([[6, 1, 1], 
               [4,-2, 5],
              [2, 8, 7]])
inverse_A3 = np.linalg.inv(A3)
inverse_A3

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

In [34]:
A4 = np.array([[3, 2, 0, 1], 
               [4, 0, 1, 2],
              [3, 0, 2, 1],
              [9, 2, 3, 1]])
inverse_A4 = np.linalg.inv(A4)
inverse_A4

array([[-0.25      ,  0.25      , -0.5       ,  0.25      ],
       [ 0.66666667, -0.5       ,  0.5       , -0.16666667],
       [ 0.16666667, -0.5       ,  1.        , -0.16666667],
       [ 0.41666667,  0.25      ,  0.5       , -0.41666667]])

1.
 [[-0.42857143  0.57142857]
 [ 0.28571429 -0.21428571]]

2.
 [[ 0.57142857 -0.42857143]
 [-0.21428571  0.28571429]]

3.
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

4.
 [[-0.25        0.25       -0.5         0.25      ]
 [ 0.66666667 -0.5         0.5        -0.16666667]
 [ 0.16666667 -0.5         1.         -0.16666667]
 [ 0.41666667  0.25        0.5        -0.41666667]]


In [ ]:
#QUIZ

In [73]:
S = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

In [74]:
v = np.array([[4], [7], [1]])

In [75]:
x = np.linalg.solve(S, v)
x

array([[4.],
       [7.],
       [1.]])

In [ ]:
#therefore vector v is in span S a=4 ,b=7,c=1 

In [69]:
import sympy as sp

In [71]:
v = np.array([[4], [7], [1]])

In [76]:
v = np.array([[4,5], 
              [1,2], 
              [0,1]])

In [79]:
matrix = Matrix([
              [4,1,0], 
              [5,2,1], 
              ])

In [80]:
matrix.rref()

(Matrix([
 [1, 0, -1/3],
 [0, 1,  4/3]]),
 (0, 1))

In [ ]:
#linearly independent

In [81]:
c1 = -1/3 c2 ,c2=-4/3 c1 ,c3 is a free variable

In [ ]:
#c2 = 4 can obtain the nontrivial solution where c3 =1

In [ ]:
#we have a free variable C so it is depndent

In [ ]:
determine whether in R3 or not check 1-linear independence 2-spaning the space

In [87]:
A = Matrix([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 1, 1] 
])

In [88]:
A.rref()


(Matrix([
 [1, 0, 0, 0],
 [0, 1, 0, 0],
 [0, 0, 1, 0],
 [0, 0, 0, 1]]),
 (0, 1, 2, 3))

In [ ]:
#not linearly independent,dosn't form basis for r3

In [ ]:
#shearing v=[[1,0],[1,1]]

In [ ]:
#INVERTING ON X-AXIS [[1,0],[0,-1]]

In [ ]:
#HOMEWORK

In [113]:
A = Matrix([
    [1, 0, 2, -5],
    [-2, 5, 0, 11],
    [2, 5, 8, 8],
])

In [114]:
A.rref()

(Matrix([
 [1, 0,   2, 0],
 [0, 1, 4/5, 0],
 [0, 0,   0, 1]]),
 (0, 1, 3))

In [ ]:
#no in this linear combination

In [115]:
matrix = Matrix([
              [1,0,1,2], 
              [1,2,2,1],
              [0,1,2,1],
              ])

In [116]:
matrix.rref()

(Matrix([
 [1, 0, 0,  1],
 [0, 1, 0, -1],
 [0, 0, 1,  1]]),
 (0, 1, 2))

In [ ]:
#R4 set is linear dependent

In [121]:
matrix = Matrix([
              [0,2,-3], 
              [3,1,1],
              [0,-1,-2],
              ])

In [124]:
e=Matrix([
              [1,0,0], 
              [0,1,0],
              [0,0,1],
              ])

In [125]:
matrix@e

Matrix([
[0,  2, -3],
[3,  1,  1],
[0, -1, -2]])

In [126]:
e=Matrix([
              [1,-1,1], 
              [0,1,2],
              [0,0,-1],
              ])

In [127]:
matrix@e

Matrix([
[0,  2, 7],
[3, -2, 4],
[0, -1, 0]])