In [1]:
import numpy as np

## Warm Up: Practice some NumPy commands:
- Create 3 * 3 array.
- Check its shape.
- Select first row.
- Select 2nd column.
- Select the 2nd element in the third column.
- Create 2*2 from the first two elements of the first 2 rows and columns.
- Create single row vector.
- Create single column vector.

## System of linear equations:
- The following system of linear equations can be represented as <b>Ax=b</b>.
- Define matrix <b>A</b> and vector <b>b</b> as numpy arrays.
- Print them out.
1. $$3x-y=2$$ $$x=4 $$
$$$$
2. $$3x-2y=7$$  $$2x-2y=2$$
$$$$
3. $$2x-2y+z=7$$  $$x+y+z=2$$  $$3x-2y-z=3$$ 

A1:
[[ 3 -1]
 [ 1  0]]
b1:[[2]
 [4]]

A2:
[[ 3 -2]
 [ 2 -2]]
b1:[[7]
 [2]]

A3:
[[ 3 -2  1]
 [ 1  1  1]
 [ 3 -2 -1]]
b1:[[7]
 [2]
 [3]]


### Find a solution for the above systems of equations using:
<b>np.linalg.inv()</b>

x1= [[ 4.]
 [10.]] 

x2= [[5.]
 [4.]] 

x3= [[ 1.]
 [-1.]
 [ 2.]]


### Find a solution for the above systems of equations using:
<b>np.linalg.solve()</b>

x1= [[ 4.]
 [10.]] 

x2= [[5.]
 [4.]] 

x3= [[ 1.]
 [-1.]
 [ 2.]]


## Using numpy arrays
- For the above systems of equations, multiply matrix <b>A</b> and vector <b>x</b> and make sure the result is <b>b</b>.

array([[2.],
       [4.]])

array([[7.],
       [2.]])

array([[7.],
       [2.],
       [3.]])

## Vector Norms

### Calculate using numpy linalg.norm().
- Calculate L1, L2, Lmax norms for the following vectors:
$$v_1=\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix},
v_2=\begin{bmatrix} 3 \\ 3 \\ 1 \\ 3 \end{bmatrix}$$
- Calculate L3 norm for the vector
$$v_3=\begin{bmatrix} 2 \\  3 \\ 4 \end{bmatrix}$$

v1:
L1: 6.0
L2: 3.7416573867739413
Lmax: 3.0

v2:
L1: 10.0
L2: 5.291502622129181
Lmax: 3.0

v3:
L3: 4.626065009182741


### Calculate L1, L2, L3, and Lmax for the following vectors:
$$v_1=\begin{bmatrix} 5 \\ 6 \end{bmatrix},
v_2=\begin{bmatrix} 4 \\ 3 \\ 2 \end{bmatrix},
v_3=\begin{bmatrix} 4 \\ 3 \\ 2 \\ 8 \\ 9 \end{bmatrix}$$

v1:
L1: 11.0
L2: 7.810249675906654
L3: 6.986368027818105
Lmax: 6.0

v2:
L1: 9.0
L2: 5.385164807134504
L3: 4.626065009182741
Lmax: 4.0

v3:
L1: 26.0
L2: 13.19090595827292
L3: 11.02473771449733
Lmax: 9.0


## Dot Product

### Calculate the dot product of the following vectors:
$$v_1=\begin{bmatrix} 2 \\ -1 \\ 5 \\ 0 \end{bmatrix} and
v_2=\begin{bmatrix} 4 \\ -3 \\ 1 \\ -1 \end{bmatrix}$$
### Calculate the dot product of the following vectors and explain the result:
$$v_1=\begin{bmatrix} 3 \\ 2 \\ -1 \\ 4 \end{bmatrix} and
v_2=\begin{bmatrix} 1 \\ -1 \\ 1 \\ 0 \end{bmatrix} $$ 

16

0

### Create two vectors in 2, 3, and 4 dimensions.
### Perform vector addition, subtraction, and dot product of these vectors.

## Matrix Operations

### Matrix Multiplication AB then Transpose the result.
$$A=\begin{bmatrix} 3&1&0 \\ 2&1&2 \end{bmatrix}, B=\begin{bmatrix} 1&3 \\ 2&5 \\ -1&3 \end{bmatrix}$$
$$A=\begin{bmatrix} 1&0&3 \\ 4&5&-1 \\ 0&0&2  \end{bmatrix}, B=\begin{bmatrix} 1\\2\\5 \end{bmatrix}$$

C1:
[[ 5 14]
 [ 2 17]]

C1_transpose:
[[ 5  2]
 [14 17]]

C2:
[[16]
 [ 9]
 [10]]

C2_transpose:
[[16  9 10]]


## Different Types of Matrices
### Create 3 by 3 and 4 by 4 identity matrices 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Create a diagonal matrix contains [2,4,5,11] numbers in its diagonal.

array([[ 2,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  5,  0],
       [ 0,  0,  0, 11]])

### Create a 5 by 5 scalar matrix of number 7

array([[7., 0., 0., 0., 0.],
       [0., 7., 0., 0., 0.],
       [0., 0., 7., 0., 0.],
       [0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 7.]])

### Using SymPy get the rref of the following matrices

Matrix([
[ 1,  0,  1,  3],
[ 2,  3,  4,  7],
[-1, -3, -3, -4]])

Matrix([
[1, 1, 1],
[1, 2, 2],
[1, 2, 3]])

Matrix([
[1,  2,  3],
[2, -1,  1],
[3,  0, -1]])

Matrix([
[ 1,  0,  1,  3],
[ 2,  3,  4,  7],
[-1, -3, -3, -4]])

(Matrix([
 [1, 0,   1,   3],
 [0, 1, 2/3, 1/3],
 [0, 0,   0,   0]]),
 (0, 1))

Matrix([
[1, 1, 1],
[1, 2, 2],
[1, 2, 3]])

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

Matrix([
[1,  2,  3],
[2, -1,  1],
[3,  0, -1]])

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

### Find the solution of the following system of linear equation using SymPy Matrix rref()
#### Write down the solution as a python note e.g., x=1, y=4, and z=10

1. $$x+y+z=6$$  $$x+2y+2z=9$$  $$x+2y+3z=10$$ 
$$$$
2. $$x+2y+3z=9$$  $$2x-y+z=8$$  $$3x-z=3$$ 

Matrix([
[1, 1, 1,  6],
[1, 2, 2,  9],
[1, 2, 3, 10]])

(Matrix([
 [1, 0, 0, 3],
 [0, 1, 0, 2],
 [0, 0, 1, 1]]),
 (0, 1, 2))

Matrix([
[1,  2,  3, 9],
[2, -1,  1, 8],
[3,  0, -1, 3]])

(Matrix([
 [1, 0, 0,  2],
 [0, 1, 0, -1],
 [0, 0, 1,  3]]),
 (0, 1, 2))

### Find the solution of the following system of linear equation using SymPy Matrix rref()
#### Write down the solution as a python note e.g., x=1, y=4, and z=10

1. $$x-2y=1$$ $$3x-6y=11 $$
$$$$
2. $$x-2y=1$$ $$3x-6y=3 $$
$$$$
3. $$x+2y+3z=6$$  $$2x+5y+2z=4$$  $$6x-3y+z=2$$ 
$$$$
4. $$2x+4y-2z=2$$  $$4x+9y-3z=8$$  $$-2x-3y+7z=10$$ 

Matrix([
[1, -2,  1],
[3, -6, 11]])

(Matrix([
 [1, -2, 0],
 [0,  0, 1]]),
 (0, 2))

Matrix([
[1, -2, 1],
[3, -6, 3]])

(Matrix([
 [1, -2, 1],
 [0,  0, 0]]),
 (0,))

Matrix([
[1,  2, 3, 6],
[2,  5, 2, 4],
[6, -3, 1, 2]])

(Matrix([
 [1, 0, 0, 0],
 [0, 1, 0, 0],
 [0, 0, 1, 2]]),
 (0, 1, 2))

Matrix([
[ 2,  4, -2,  2],
[ 4,  9, -3,  8],
[-2, -3,  7, 10]])

(Matrix([
 [1, 0, 0, -1],
 [0, 1, 0,  2],
 [0, 0, 1,  2]]),
 (0, 1, 2))